tests: port U+10000+ to AIX 7.2
* tests/hangul-syllable, tests/surrogate-search:
32-bit AIX has WCHAR_MAX == 0xFFFF, and so cannot handle
U+10000 and greater.  Skip tests involving such chars
on this platform.

diff --git a/tests/hangul-syllable b/tests/hangul-syllable
--- a/tests/hangul-syllable
+++ b/tests/hangul-syllable
@@ -99,6 +99,15 @@ for i in 355; do
     done
   done
 done
+
+# On platforms like 32-bit AIX where WCHAR_MAX == 0xFFFF, skip checks
+# where the corresponding Unicode characters are not supported.
+if test $fail -eq 0; then
+  printf '\360\220\200\200\n' >in || framework_failure_
+  grep '^.$' in >out 2>&1 || fail=1
+  cmp in out || skip_ 'platform does not support U+10000'
+fi
+
 for i in 360; do
   for j in 220 277; do
     for k in 200 277; do
